added weight service
coungard/delivery-club pull request #23
Opened 2024-05-20 17:17 UTC by Konstantin-Pavlov

2024-07-21 15:25 UTC, coungard requested changes
Need fixes

2024-07-21 15:25 UTC, coungard commented on order-service/build/generated/sources/annotationProcessor/java/main/com/coungard/mapper/WeightMapperImpl.java
This class must be unstagable

2024-07-21 15:25 UTC, coungard commented on order-service/src/main/java/com/coungard/config/SecurityConfig.java
This file is already formatted

2024-07-21 15:25 UTC, coungard commented on order-service/src/main/java/com/coungard/controller/ControllerAdvice.java
RestControllerAdvice is already exists in exception package

2024-07-21 15:25 UTC, coungard commented on order-service/src/main/java/com/coungard/controller/OrderController.java
No need format here

2024-07-22 18:52 UTC, Konstantin-Pavlov commented on order-service/src/main/java/com/coungard/controller/OrderController.java
done

2024-07-22 18:52 UTC, Konstantin-Pavlov commented on order-service/src/main/java/com/coungard/controller/ControllerAdvice.java
delete this class

2024-07-22 18:53 UTC, Konstantin-Pavlov commented on order-service/src/main/java/com/coungard/config/SecurityConfig.java
fix formatting

2024-07-22 18:53 UTC, Konstantin-Pavlov commented on order-service/build/generated/sources/annotationProcessor/java/main/com/coungard/mapper/WeightMapperImpl.java
delete from git index and github

2024-07-22 19:02 UTC, merged